# Don't change this line unless you know what you're doing
default https://raw.githubusercontent.com/muscaa/quill-packages/main/repository.json

# Extra repositories in "${namespace} ${url}" format
# ...
